name: Validate Ubuntu
on: [push, pull_request]
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.13, 12, 14]
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: ▶️ Run setup script
        run: npm run setup
